// Code generated for mbakhodurov service
// © mbakhodurov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/bson"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mbakhodurov/homeworks/week3/inventory/internal/model"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, inventoryInfo
func (_m *InventoryRepository) Create(ctx context.Context, inventoryInfo model.Inventory) error {
	ret := _m.Called(ctx, inventoryInfo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Inventory) error); ok {
		r0 = rf(ctx, inventoryInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InventoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - inventoryInfo model.Inventory
func (_e *InventoryRepository_Expecter) Create(ctx interface{}, inventoryInfo interface{}) *InventoryRepository_Create_Call {
	return &InventoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, inventoryInfo)}
}

func (_c *InventoryRepository_Create_Call) Run(run func(ctx context.Context, inventoryInfo model.Inventory)) *InventoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Inventory))
	})
	return _c
}

func (_c *InventoryRepository_Create_Call) Return(_a0 error) *InventoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_Create_Call) RunAndReturn(run func(context.Context, model.Inventory) error) *InventoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *InventoryRepository) Delete(ctx context.Context, uuid string) (int64, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InventoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryRepository_Expecter) Delete(ctx interface{}, uuid interface{}) *InventoryRepository_Delete_Call {
	return &InventoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *InventoryRepository_Delete_Call) Run(run func(ctx context.Context, uuid string)) *InventoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_Delete_Call) Return(_a0 int64, _a1 error) *InventoryRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_Delete_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *InventoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *InventoryRepository) GetAll(ctx context.Context) ([]model.Inventory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Inventory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Inventory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type InventoryRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InventoryRepository_Expecter) GetAll(ctx interface{}) *InventoryRepository_GetAll_Call {
	return &InventoryRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *InventoryRepository_GetAll_Call) Run(run func(ctx context.Context)) *InventoryRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InventoryRepository_GetAll_Call) Return(_a0 []model.Inventory, _a1 error) *InventoryRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Inventory, error)) *InventoryRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *InventoryRepository) GetByUUID(ctx context.Context, uuid string) (model.Inventory, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Inventory, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Inventory); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Inventory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type InventoryRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryRepository_Expecter) GetByUUID(ctx interface{}, uuid interface{}) *InventoryRepository_GetByUUID_Call {
	return &InventoryRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid)}
}

func (_c *InventoryRepository_GetByUUID_Call) Run(run func(ctx context.Context, uuid string)) *InventoryRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_GetByUUID_Call) Return(_a0 model.Inventory, _a1 error) *InventoryRepository_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (model.Inventory, error)) *InventoryRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListInventory provides a mock function with given fields: ctx, filter
func (_m *InventoryRepository) ListInventory(ctx context.Context, filter model.InventoryFilter) ([]model.Inventory, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListInventory")
	}

	var r0 []model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryFilter) ([]model.Inventory, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryFilter) []model.Inventory); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.InventoryFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_ListInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInventory'
type InventoryRepository_ListInventory_Call struct {
	*mock.Call
}

// ListInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.InventoryFilter
func (_e *InventoryRepository_Expecter) ListInventory(ctx interface{}, filter interface{}) *InventoryRepository_ListInventory_Call {
	return &InventoryRepository_ListInventory_Call{Call: _e.mock.On("ListInventory", ctx, filter)}
}

func (_c *InventoryRepository_ListInventory_Call) Run(run func(ctx context.Context, filter model.InventoryFilter)) *InventoryRepository_ListInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.InventoryFilter))
	})
	return _c
}

func (_c *InventoryRepository_ListInventory_Call) Return(_a0 []model.Inventory, _a1 error) *InventoryRepository_ListInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_ListInventory_Call) RunAndReturn(run func(context.Context, model.InventoryFilter) ([]model.Inventory, error)) *InventoryRepository_ListInventory_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uuid, set
func (_m *InventoryRepository) Update(ctx context.Context, uuid string, set bson.M) error {
	ret := _m.Called(ctx, uuid, set)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bson.M) error); ok {
		r0 = rf(ctx, uuid, set)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InventoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - set bson.M
func (_e *InventoryRepository_Expecter) Update(ctx interface{}, uuid interface{}, set interface{}) *InventoryRepository_Update_Call {
	return &InventoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, uuid, set)}
}

func (_c *InventoryRepository_Update_Call) Run(run func(ctx context.Context, uuid string, set bson.M)) *InventoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bson.M))
	})
	return _c
}

func (_c *InventoryRepository_Update_Call) Return(_a0 error) *InventoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_Update_Call) RunAndReturn(run func(context.Context, string, bson.M) error) *InventoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
