// Code generated for mbakhodurov service
// © mbakhodurov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mbakhodurov/homeworks/week3/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, part
func (_m *InventoryService) Create(ctx context.Context, part model.InventoryInfo) (string, error) {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryInfo) (string, error)); ok {
		return rf(ctx, part)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryInfo) string); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.InventoryInfo) error); ok {
		r1 = rf(ctx, part)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InventoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - part model.InventoryInfo
func (_e *InventoryService_Expecter) Create(ctx interface{}, part interface{}) *InventoryService_Create_Call {
	return &InventoryService_Create_Call{Call: _e.mock.On("Create", ctx, part)}
}

func (_c *InventoryService_Create_Call) Run(run func(ctx context.Context, part model.InventoryInfo)) *InventoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.InventoryInfo))
	})
	return _c
}

func (_c *InventoryService_Create_Call) Return(_a0 string, _a1 error) *InventoryService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Create_Call) RunAndReturn(run func(context.Context, model.InventoryInfo) (string, error)) *InventoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *InventoryService) Delete(ctx context.Context, uuid string) (int64, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InventoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryService_Expecter) Delete(ctx interface{}, uuid interface{}) *InventoryService_Delete_Call {
	return &InventoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *InventoryService_Delete_Call) Run(run func(ctx context.Context, uuid string)) *InventoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_Delete_Call) Return(_a0 int64, _a1 error) *InventoryService_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Delete_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *InventoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *InventoryService) GetAll(ctx context.Context) ([]model.Inventory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Inventory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Inventory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type InventoryService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InventoryService_Expecter) GetAll(ctx interface{}) *InventoryService_GetAll_Call {
	return &InventoryService_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *InventoryService_GetAll_Call) Run(run func(ctx context.Context)) *InventoryService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InventoryService_GetAll_Call) Return(_a0 []model.Inventory, _a1 error) *InventoryService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Inventory, error)) *InventoryService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *InventoryService) GetByUUID(ctx context.Context, uuid string) (model.Inventory, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Inventory, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Inventory); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Inventory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type InventoryService_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryService_Expecter) GetByUUID(ctx interface{}, uuid interface{}) *InventoryService_GetByUUID_Call {
	return &InventoryService_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid)}
}

func (_c *InventoryService_GetByUUID_Call) Run(run func(ctx context.Context, uuid string)) *InventoryService_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_GetByUUID_Call) Return(_a0 model.Inventory, _a1 error) *InventoryService_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (model.Inventory, error)) *InventoryService_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *InventoryService) ListParts(ctx context.Context, filter model.InventoryFilter) ([]model.Inventory, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryFilter) ([]model.Inventory, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.InventoryFilter) []model.Inventory); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.InventoryFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.InventoryFilter
func (_e *InventoryService_Expecter) ListParts(ctx interface{}, filter interface{}) *InventoryService_ListParts_Call {
	return &InventoryService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *InventoryService_ListParts_Call) Run(run func(ctx context.Context, filter model.InventoryFilter)) *InventoryService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.InventoryFilter))
	})
	return _c
}

func (_c *InventoryService_ListParts_Call) Return(_a0 []model.Inventory, _a1 error) *InventoryService_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_ListParts_Call) RunAndReturn(run func(context.Context, model.InventoryFilter) ([]model.Inventory, error)) *InventoryService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uuid, inventortUpdateInfo
func (_m *InventoryService) Update(ctx context.Context, uuid string, inventortUpdateInfo model.InventoryInfoUpdate) error {
	ret := _m.Called(ctx, uuid, inventortUpdateInfo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.InventoryInfoUpdate) error); ok {
		r0 = rf(ctx, uuid, inventortUpdateInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InventoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - inventortUpdateInfo model.InventoryInfoUpdate
func (_e *InventoryService_Expecter) Update(ctx interface{}, uuid interface{}, inventortUpdateInfo interface{}) *InventoryService_Update_Call {
	return &InventoryService_Update_Call{Call: _e.mock.On("Update", ctx, uuid, inventortUpdateInfo)}
}

func (_c *InventoryService_Update_Call) Run(run func(ctx context.Context, uuid string, inventortUpdateInfo model.InventoryInfoUpdate)) *InventoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.InventoryInfoUpdate))
	})
	return _c
}

func (_c *InventoryService_Update_Call) Return(_a0 error) *InventoryService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryService_Update_Call) RunAndReturn(run func(context.Context, string, model.InventoryInfoUpdate) error) *InventoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
