// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_CATEGORY_ENGINE      Category = 1
	Category_CATEGORY_FUEL        Category = 2
	Category_CATEGORY_PORTHOLE    Category = 3
	Category_CATEGORY_WING        Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_ENGINE",
		2: "CATEGORY_FUEL",
		3: "CATEGORY_PORTHOLE",
		4: "CATEGORY_WING",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_ENGINE":      1,
		"CATEGORY_FUEL":        2,
		"CATEGORY_PORTHOLE":    3,
		"CATEGORY_WING":        4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

type ListPartInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PartsFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartInventoryRequest) Reset() {
	*x = ListPartInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartInventoryRequest) ProtoMessage() {}

func (x *ListPartInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartInventoryRequest.ProtoReflect.Descriptor instead.
func (*ListPartInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ListPartInventoryRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type PartsFilter struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuids                 []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Names                 []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Categories            []Category             `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=inventory.v1.Category" json:"categories,omitempty"`
	ManufacturerCountries []string               `protobuf:"bytes,4,rep,name=manufacturer_countries,json=manufacturerCountries,proto3" json:"manufacturer_countries,omitempty"`
	Tags                  []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PartsFilter) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PartsFilter) GetManufacturerCountries() []string {
	if x != nil {
		return x.ManufacturerCountries
	}
	return nil
}

func (x *PartsFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListPartInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     []*Inventory           `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartInventoryResponse) Reset() {
	*x = ListPartInventoryResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartInventoryResponse) ProtoMessage() {}

func (x *ListPartInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartInventoryResponse.ProtoReflect.Descriptor instead.
func (*ListPartInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ListPartInventoryResponse) GetInventory() []*Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *ListPartInventoryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type DeleteInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryRequest) Reset() {
	*x = DeleteInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryRequest) ProtoMessage() {}

func (x *DeleteInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteInventoryRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UpdateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UpdateInfo    *InventoryUpdateInfo   `protobuf:"bytes,2,opt,name=update_info,json=updateInfo,proto3" json:"update_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryRequest) Reset() {
	*x = UpdateInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryRequest) ProtoMessage() {}

func (x *UpdateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInventoryRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateInventoryRequest) GetUpdateInfo() *InventoryUpdateInfo {
	if x != nil {
		return x.UpdateInfo
	}
	return nil
}

type InventoryUpdateInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity *wrapperspb.Int64Value  `protobuf:"bytes,4,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      Category                `protobuf:"varint,5,opt,name=category,proto3,enum=inventory.v1.Category" json:"category,omitempty"`
	Dimensions    *Dimensions             `protobuf:"bytes,6,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Manufacturer  *Manufacturer           `protobuf:"bytes,7,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryUpdateInfo) Reset() {
	*x = InventoryUpdateInfo{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdateInfo) ProtoMessage() {}

func (x *InventoryUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdateInfo.ProtoReflect.Descriptor instead.
func (*InventoryUpdateInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryUpdateInfo) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *InventoryUpdateInfo) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *InventoryUpdateInfo) GetPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *InventoryUpdateInfo) GetStockQuantity() *wrapperspb.Int64Value {
	if x != nil {
		return x.StockQuantity
	}
	return nil
}

func (x *InventoryUpdateInfo) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *InventoryUpdateInfo) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *InventoryUpdateInfo) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

type GetAllInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInventoryRequest) Reset() {
	*x = GetAllInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInventoryRequest) ProtoMessage() {}

func (x *GetAllInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

type GetAllInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     []*Inventory           `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInventoryResponse) Reset() {
	*x = GetAllInventoryResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInventoryResponse) ProtoMessage() {}

func (x *GetAllInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllInventoryResponse) GetInventory() []*Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *GetAllInventoryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetInventoryByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByUUIDRequest) Reset() {
	*x = GetInventoryByUUIDRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByUUIDRequest) ProtoMessage() {}

func (x *GetInventoryByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *GetInventoryByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *GetInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type CreateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *InventoryInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *CreateInventoryRequest) GetInfo() *InventoryInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryResponse) Reset() {
	*x = CreateInventoryResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryResponse) ProtoMessage() {}

func (x *CreateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryResponse.ProtoReflect.Descriptor instead.
func (*CreateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CreateInventoryResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	InventoryInfo *InventoryInfo         `protobuf:"bytes,2,opt,name=inventory_info,json=inventoryInfo,proto3" json:"inventory_info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *Inventory) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Inventory) GetInventoryInfo() *InventoryInfo {
	if x != nil {
		return x.InventoryInfo
	}
	return nil
}

func (x *Inventory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Inventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Inventory) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type InventoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int64                  `protobuf:"varint,4,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      Category               `protobuf:"varint,5,opt,name=category,proto3,enum=inventory.v1.Category" json:"category,omitempty"`
	Dimensions    *Dimensions            `protobuf:"bytes,6,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Manufacturer  *Manufacturer          `protobuf:"bytes,7,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]*Value      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryInfo) Reset() {
	*x = InventoryInfo{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryInfo) ProtoMessage() {}

func (x *InventoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryInfo.ProtoReflect.Descriptor instead.
func (*InventoryInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *InventoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InventoryInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InventoryInfo) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *InventoryInfo) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *InventoryInfo) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *InventoryInfo) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *InventoryInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InventoryInfo) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimensions) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_BoolValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"M\n" +
	"\x18ListPartInventoryRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.inventory.v1.PartsFilterR\x06filter\"\xbc\x01\n" +
	"\vPartsFilter\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x126\n" +
	"\n" +
	"categories\x18\x03 \x03(\x0e2\x16.inventory.v1.CategoryR\n" +
	"categories\x125\n" +
	"\x16manufacturer_countries\x18\x04 \x03(\tR\x15manufacturerCountries\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"s\n" +
	"\x19ListPartInventoryResponse\x125\n" +
	"\tinventory\x18\x01 \x03(\v2\x17.inventory.v1.InventoryR\tinventory\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"5\n" +
	"\x0eDeleteResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\",\n" +
	"\x16DeleteInventoryRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"p\n" +
	"\x16UpdateInventoryRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12B\n" +
	"\vupdate_info\x18\x02 \x01(\v2!.inventory.v1.InventoryUpdateInfoR\n" +
	"updateInfo\"\xad\x03\n" +
	"\x13InventoryUpdateInfo\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05price\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05price\x12B\n" +
	"\x0estock_quantity\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\rstockQuantity\x122\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x16.inventory.v1.CategoryR\bcategory\x128\n" +
	"\n" +
	"dimensions\x18\x06 \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12>\n" +
	"\fmanufacturer\x18\a \x01(\v2\x1a.inventory.v1.ManufacturerR\fmanufacturer\"\x18\n" +
	"\x16GetAllInventoryRequest\"q\n" +
	"\x17GetAllInventoryResponse\x125\n" +
	"\tinventory\x18\x01 \x03(\v2\x17.inventory.v1.InventoryR\tinventory\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"/\n" +
	"\x19GetInventoryByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"M\n" +
	"\x14GetInventoryResponse\x125\n" +
	"\tinventory\x18\x01 \x01(\v2\x17.inventory.v1.InventoryR\tinventory\"I\n" +
	"\x16CreateInventoryRequest\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryInfoR\x04info\"-\n" +
	"\x17CreateInventoryResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x94\x02\n" +
	"\tInventory\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12B\n" +
	"\x0einventory_info\x18\x02 \x01(\v2\x1b.inventory.v1.InventoryInfoR\rinventoryInfo\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xe8\x03\n" +
	"\rInventoryInfo\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x04 \x01(\x03R\rstockQuantity\x122\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x16.inventory.v1.CategoryR\bcategory\x128\n" +
	"\n" +
	"dimensions\x18\x06 \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12>\n" +
	"\fmanufacturer\x18\a \x01(\v2\x1a.inventory.v1.ManufacturerR\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12E\n" +
	"\bmetadata\x18\t \x03(\v2).inventory.v1.InventoryInfo.MetadataEntryR\bmetadata\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.inventory.v1.ValueR\x05value:\x028\x01\"j\n" +
	"\n" +
	"Dimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"V\n" +
	"\fManufacturer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\x9d\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\x06\n" +
	"\x04kind*v\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCATEGORY_ENGINE\x10\x01\x12\x11\n" +
	"\rCATEGORY_FUEL\x10\x02\x12\x15\n" +
	"\x11CATEGORY_PORTHOLE\x10\x03\x12\x11\n" +
	"\rCATEGORY_WING\x10\x042\x81\x06\n" +
	"\x10InventoryService\x12\x7f\n" +
	"\x11ListPartInventory\x12&.inventory.v1.ListPartInventoryRequest\x1a'.inventory.v1.ListPartInventoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/listparts\x12|\n" +
	"\x0fCreateInventory\x12$.inventory.v1.CreateInventoryRequest\x1a%.inventory.v1.CreateInventoryResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/inventory\x12\x83\x01\n" +
	"\x12GetInventoryByUUID\x12'.inventory.v1.GetInventoryByUUIDRequest\x1a\".inventory.v1.GetInventoryResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/inventory/{uuid}\x12y\n" +
	"\x0fGetAllInventory\x12$.inventory.v1.GetAllInventoryRequest\x1a%.inventory.v1.GetAllInventoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/inventory\x12t\n" +
	"\x0fUpdateInventory\x12$.inventory.v1.UpdateInventoryRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/api/v1/inventory/{uuid}\x12w\n" +
	"\x0fDeleteInventory\x12$.inventory.v1.DeleteInventoryRequest\x1a\x1c.inventory.v1.DeleteResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/inventory/{uuid}BSZQgithub.com/mbakhodurov/homeworks/week3/shared/pkg/proto/inventory/v1;inventory_v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(Category)(0),                     // 0: inventory.v1.Category
	(*ListPartInventoryRequest)(nil),  // 1: inventory.v1.ListPartInventoryRequest
	(*PartsFilter)(nil),               // 2: inventory.v1.PartsFilter
	(*ListPartInventoryResponse)(nil), // 3: inventory.v1.ListPartInventoryResponse
	(*DeleteResponse)(nil),            // 4: inventory.v1.DeleteResponse
	(*DeleteInventoryRequest)(nil),    // 5: inventory.v1.DeleteInventoryRequest
	(*UpdateInventoryRequest)(nil),    // 6: inventory.v1.UpdateInventoryRequest
	(*InventoryUpdateInfo)(nil),       // 7: inventory.v1.InventoryUpdateInfo
	(*GetAllInventoryRequest)(nil),    // 8: inventory.v1.GetAllInventoryRequest
	(*GetAllInventoryResponse)(nil),   // 9: inventory.v1.GetAllInventoryResponse
	(*GetInventoryByUUIDRequest)(nil), // 10: inventory.v1.GetInventoryByUUIDRequest
	(*GetInventoryResponse)(nil),      // 11: inventory.v1.GetInventoryResponse
	(*CreateInventoryRequest)(nil),    // 12: inventory.v1.CreateInventoryRequest
	(*CreateInventoryResponse)(nil),   // 13: inventory.v1.CreateInventoryResponse
	(*Inventory)(nil),                 // 14: inventory.v1.Inventory
	(*InventoryInfo)(nil),             // 15: inventory.v1.InventoryInfo
	(*Dimensions)(nil),                // 16: inventory.v1.Dimensions
	(*Manufacturer)(nil),              // 17: inventory.v1.Manufacturer
	(*Value)(nil),                     // 18: inventory.v1.Value
	nil,                               // 19: inventory.v1.InventoryInfo.MetadataEntry
	(*wrapperspb.StringValue)(nil),    // 20: google.protobuf.StringValue
	(*wrapperspb.DoubleValue)(nil),    // 21: google.protobuf.DoubleValue
	(*wrapperspb.Int64Value)(nil),     // 22: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 24: google.protobuf.Empty
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	2,  // 0: inventory.v1.ListPartInventoryRequest.filter:type_name -> inventory.v1.PartsFilter
	0,  // 1: inventory.v1.PartsFilter.categories:type_name -> inventory.v1.Category
	14, // 2: inventory.v1.ListPartInventoryResponse.inventory:type_name -> inventory.v1.Inventory
	7,  // 3: inventory.v1.UpdateInventoryRequest.update_info:type_name -> inventory.v1.InventoryUpdateInfo
	20, // 4: inventory.v1.InventoryUpdateInfo.name:type_name -> google.protobuf.StringValue
	20, // 5: inventory.v1.InventoryUpdateInfo.description:type_name -> google.protobuf.StringValue
	21, // 6: inventory.v1.InventoryUpdateInfo.price:type_name -> google.protobuf.DoubleValue
	22, // 7: inventory.v1.InventoryUpdateInfo.stock_quantity:type_name -> google.protobuf.Int64Value
	0,  // 8: inventory.v1.InventoryUpdateInfo.category:type_name -> inventory.v1.Category
	16, // 9: inventory.v1.InventoryUpdateInfo.dimensions:type_name -> inventory.v1.Dimensions
	17, // 10: inventory.v1.InventoryUpdateInfo.manufacturer:type_name -> inventory.v1.Manufacturer
	14, // 11: inventory.v1.GetAllInventoryResponse.inventory:type_name -> inventory.v1.Inventory
	14, // 12: inventory.v1.GetInventoryResponse.inventory:type_name -> inventory.v1.Inventory
	15, // 13: inventory.v1.CreateInventoryRequest.info:type_name -> inventory.v1.InventoryInfo
	15, // 14: inventory.v1.Inventory.inventory_info:type_name -> inventory.v1.InventoryInfo
	23, // 15: inventory.v1.Inventory.created_at:type_name -> google.protobuf.Timestamp
	23, // 16: inventory.v1.Inventory.updated_at:type_name -> google.protobuf.Timestamp
	23, // 17: inventory.v1.Inventory.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 18: inventory.v1.InventoryInfo.category:type_name -> inventory.v1.Category
	16, // 19: inventory.v1.InventoryInfo.dimensions:type_name -> inventory.v1.Dimensions
	17, // 20: inventory.v1.InventoryInfo.manufacturer:type_name -> inventory.v1.Manufacturer
	19, // 21: inventory.v1.InventoryInfo.metadata:type_name -> inventory.v1.InventoryInfo.MetadataEntry
	18, // 22: inventory.v1.InventoryInfo.MetadataEntry.value:type_name -> inventory.v1.Value
	1,  // 23: inventory.v1.InventoryService.ListPartInventory:input_type -> inventory.v1.ListPartInventoryRequest
	12, // 24: inventory.v1.InventoryService.CreateInventory:input_type -> inventory.v1.CreateInventoryRequest
	10, // 25: inventory.v1.InventoryService.GetInventoryByUUID:input_type -> inventory.v1.GetInventoryByUUIDRequest
	8,  // 26: inventory.v1.InventoryService.GetAllInventory:input_type -> inventory.v1.GetAllInventoryRequest
	6,  // 27: inventory.v1.InventoryService.UpdateInventory:input_type -> inventory.v1.UpdateInventoryRequest
	5,  // 28: inventory.v1.InventoryService.DeleteInventory:input_type -> inventory.v1.DeleteInventoryRequest
	3,  // 29: inventory.v1.InventoryService.ListPartInventory:output_type -> inventory.v1.ListPartInventoryResponse
	13, // 30: inventory.v1.InventoryService.CreateInventory:output_type -> inventory.v1.CreateInventoryResponse
	11, // 31: inventory.v1.InventoryService.GetInventoryByUUID:output_type -> inventory.v1.GetInventoryResponse
	9,  // 32: inventory.v1.InventoryService.GetAllInventory:output_type -> inventory.v1.GetAllInventoryResponse
	24, // 33: inventory.v1.InventoryService.UpdateInventory:output_type -> google.protobuf.Empty
	4,  // 34: inventory.v1.InventoryService.DeleteInventory:output_type -> inventory.v1.DeleteResponse
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	file_inventory_v1_inventory_proto_msgTypes[17].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
