// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeleteResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeleteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeleteResponseMultiError,
// or nil if none found.
func (m *DeleteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeletedCount

	if len(errors) > 0 {
		return DeleteResponseMultiError(errors)
	}

	return nil
}

// DeleteResponseMultiError is an error wrapping multiple validation errors
// returned by DeleteResponse.ValidateAll() if the designated constraints
// aren't met.
type DeleteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteResponseMultiError) AllErrors() []error { return m }

// DeleteResponseValidationError is the validation error returned by
// DeleteResponse.Validate if the designated constraints aren't met.
type DeleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteResponseValidationError) ErrorName() string { return "DeleteResponseValidationError" }

// Error satisfies the builtin error interface
func (e DeleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteResponseValidationError{}

// Validate checks the field values on DeleteInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteInventoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteInventoryRequestMultiError, or nil if none found.
func (m *DeleteInventoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteInventoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if len(errors) > 0 {
		return DeleteInventoryRequestMultiError(errors)
	}

	return nil
}

// DeleteInventoryRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteInventoryRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteInventoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteInventoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteInventoryRequestMultiError) AllErrors() []error { return m }

// DeleteInventoryRequestValidationError is the validation error returned by
// DeleteInventoryRequest.Validate if the designated constraints aren't met.
type DeleteInventoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteInventoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteInventoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteInventoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteInventoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteInventoryRequestValidationError) ErrorName() string {
	return "DeleteInventoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteInventoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteInventoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteInventoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteInventoryRequestValidationError{}

// Validate checks the field values on UpdateInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateInventoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateInventoryRequestMultiError, or nil if none found.
func (m *UpdateInventoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateInventoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if all {
		switch v := interface{}(m.GetUpdateInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateInventoryRequestValidationError{
					field:  "UpdateInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateInventoryRequestValidationError{
					field:  "UpdateInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateInventoryRequestValidationError{
				field:  "UpdateInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateInventoryRequestMultiError(errors)
	}

	return nil
}

// UpdateInventoryRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateInventoryRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateInventoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateInventoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateInventoryRequestMultiError) AllErrors() []error { return m }

// UpdateInventoryRequestValidationError is the validation error returned by
// UpdateInventoryRequest.Validate if the designated constraints aren't met.
type UpdateInventoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateInventoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateInventoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateInventoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateInventoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateInventoryRequestValidationError) ErrorName() string {
	return "UpdateInventoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateInventoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateInventoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateInventoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateInventoryRequestValidationError{}

// Validate checks the field values on InventoryUpdateInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InventoryUpdateInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InventoryUpdateInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InventoryUpdateInfoMultiError, or nil if none found.
func (m *InventoryUpdateInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *InventoryUpdateInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetName()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Name",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Name",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetName()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "Name",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDescription()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDescription()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "Description",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPrice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Price",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Price",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "Price",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStockQuantity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "StockQuantity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "StockQuantity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStockQuantity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "StockQuantity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Category

	if all {
		switch v := interface{}(m.GetDimensions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDimensions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "Dimensions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetManufacturer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryUpdateInfoValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManufacturer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryUpdateInfoValidationError{
				field:  "Manufacturer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InventoryUpdateInfoMultiError(errors)
	}

	return nil
}

// InventoryUpdateInfoMultiError is an error wrapping multiple validation
// errors returned by InventoryUpdateInfo.ValidateAll() if the designated
// constraints aren't met.
type InventoryUpdateInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InventoryUpdateInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InventoryUpdateInfoMultiError) AllErrors() []error { return m }

// InventoryUpdateInfoValidationError is the validation error returned by
// InventoryUpdateInfo.Validate if the designated constraints aren't met.
type InventoryUpdateInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InventoryUpdateInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InventoryUpdateInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InventoryUpdateInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InventoryUpdateInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InventoryUpdateInfoValidationError) ErrorName() string {
	return "InventoryUpdateInfoValidationError"
}

// Error satisfies the builtin error interface
func (e InventoryUpdateInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInventoryUpdateInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InventoryUpdateInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InventoryUpdateInfoValidationError{}

// Validate checks the field values on GetAllInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllInventoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllInventoryRequestMultiError, or nil if none found.
func (m *GetAllInventoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllInventoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetAllInventoryRequestMultiError(errors)
	}

	return nil
}

// GetAllInventoryRequestMultiError is an error wrapping multiple validation
// errors returned by GetAllInventoryRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAllInventoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllInventoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllInventoryRequestMultiError) AllErrors() []error { return m }

// GetAllInventoryRequestValidationError is the validation error returned by
// GetAllInventoryRequest.Validate if the designated constraints aren't met.
type GetAllInventoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllInventoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllInventoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllInventoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllInventoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllInventoryRequestValidationError) ErrorName() string {
	return "GetAllInventoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllInventoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllInventoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllInventoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllInventoryRequestValidationError{}

// Validate checks the field values on GetAllInventoryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllInventoryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllInventoryResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllInventoryResponseMultiError, or nil if none found.
func (m *GetAllInventoryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllInventoryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetInventory() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAllInventoryResponseValidationError{
						field:  fmt.Sprintf("Inventory[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAllInventoryResponseValidationError{
						field:  fmt.Sprintf("Inventory[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAllInventoryResponseValidationError{
					field:  fmt.Sprintf("Inventory[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return GetAllInventoryResponseMultiError(errors)
	}

	return nil
}

// GetAllInventoryResponseMultiError is an error wrapping multiple validation
// errors returned by GetAllInventoryResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAllInventoryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllInventoryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllInventoryResponseMultiError) AllErrors() []error { return m }

// GetAllInventoryResponseValidationError is the validation error returned by
// GetAllInventoryResponse.Validate if the designated constraints aren't met.
type GetAllInventoryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllInventoryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllInventoryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllInventoryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllInventoryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllInventoryResponseValidationError) ErrorName() string {
	return "GetAllInventoryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllInventoryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllInventoryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllInventoryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllInventoryResponseValidationError{}

// Validate checks the field values on GetInventoryByUUIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetInventoryByUUIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetInventoryByUUIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetInventoryByUUIDRequestMultiError, or nil if none found.
func (m *GetInventoryByUUIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetInventoryByUUIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if len(errors) > 0 {
		return GetInventoryByUUIDRequestMultiError(errors)
	}

	return nil
}

// GetInventoryByUUIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetInventoryByUUIDRequest.ValidateAll() if the
// designated constraints aren't met.
type GetInventoryByUUIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetInventoryByUUIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetInventoryByUUIDRequestMultiError) AllErrors() []error { return m }

// GetInventoryByUUIDRequestValidationError is the validation error returned by
// GetInventoryByUUIDRequest.Validate if the designated constraints aren't met.
type GetInventoryByUUIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetInventoryByUUIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetInventoryByUUIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetInventoryByUUIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetInventoryByUUIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetInventoryByUUIDRequestValidationError) ErrorName() string {
	return "GetInventoryByUUIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetInventoryByUUIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetInventoryByUUIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetInventoryByUUIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetInventoryByUUIDRequestValidationError{}

// Validate checks the field values on GetInventoryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetInventoryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetInventoryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetInventoryResponseMultiError, or nil if none found.
func (m *GetInventoryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetInventoryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInventory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetInventoryResponseValidationError{
					field:  "Inventory",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetInventoryResponseValidationError{
					field:  "Inventory",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInventory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetInventoryResponseValidationError{
				field:  "Inventory",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetInventoryResponseMultiError(errors)
	}

	return nil
}

// GetInventoryResponseMultiError is an error wrapping multiple validation
// errors returned by GetInventoryResponse.ValidateAll() if the designated
// constraints aren't met.
type GetInventoryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetInventoryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetInventoryResponseMultiError) AllErrors() []error { return m }

// GetInventoryResponseValidationError is the validation error returned by
// GetInventoryResponse.Validate if the designated constraints aren't met.
type GetInventoryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetInventoryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetInventoryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetInventoryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetInventoryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetInventoryResponseValidationError) ErrorName() string {
	return "GetInventoryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetInventoryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetInventoryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetInventoryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetInventoryResponseValidationError{}

// Validate checks the field values on CreateInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInventoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInventoryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInventoryRequestMultiError, or nil if none found.
func (m *CreateInventoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInventoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInventoryRequestValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInventoryRequestValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInventoryRequestValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInventoryRequestMultiError(errors)
	}

	return nil
}

// CreateInventoryRequestMultiError is an error wrapping multiple validation
// errors returned by CreateInventoryRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateInventoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInventoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInventoryRequestMultiError) AllErrors() []error { return m }

// CreateInventoryRequestValidationError is the validation error returned by
// CreateInventoryRequest.Validate if the designated constraints aren't met.
type CreateInventoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInventoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInventoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInventoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInventoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInventoryRequestValidationError) ErrorName() string {
	return "CreateInventoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInventoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInventoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInventoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInventoryRequestValidationError{}

// Validate checks the field values on CreateInventoryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInventoryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInventoryResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInventoryResponseMultiError, or nil if none found.
func (m *CreateInventoryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInventoryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if len(errors) > 0 {
		return CreateInventoryResponseMultiError(errors)
	}

	return nil
}

// CreateInventoryResponseMultiError is an error wrapping multiple validation
// errors returned by CreateInventoryResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateInventoryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInventoryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInventoryResponseMultiError) AllErrors() []error { return m }

// CreateInventoryResponseValidationError is the validation error returned by
// CreateInventoryResponse.Validate if the designated constraints aren't met.
type CreateInventoryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInventoryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInventoryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInventoryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInventoryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInventoryResponseValidationError) ErrorName() string {
	return "CreateInventoryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInventoryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInventoryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInventoryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInventoryResponseValidationError{}

// Validate checks the field values on Inventory with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Inventory) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Inventory with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InventoryMultiError, or nil
// if none found.
func (m *Inventory) ValidateAll() error {
	return m.validate(true)
}

func (m *Inventory) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if all {
		switch v := interface{}(m.GetInventoryInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "InventoryInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "InventoryInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInventoryInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryValidationError{
				field:  "InventoryInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryValidationError{
				field:  "DeletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InventoryMultiError(errors)
	}

	return nil
}

// InventoryMultiError is an error wrapping multiple validation errors returned
// by Inventory.ValidateAll() if the designated constraints aren't met.
type InventoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InventoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InventoryMultiError) AllErrors() []error { return m }

// InventoryValidationError is the validation error returned by
// Inventory.Validate if the designated constraints aren't met.
type InventoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InventoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InventoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InventoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InventoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InventoryValidationError) ErrorName() string { return "InventoryValidationError" }

// Error satisfies the builtin error interface
func (e InventoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInventory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InventoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InventoryValidationError{}

// Validate checks the field values on InventoryInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *InventoryInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InventoryInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InventoryInfoMultiError, or
// nil if none found.
func (m *InventoryInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *InventoryInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 50 {
		err := InventoryInfoValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	// no validation rules for Price

	// no validation rules for StockQuantity

	// no validation rules for Category

	if all {
		switch v := interface{}(m.GetDimensions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryInfoValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryInfoValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDimensions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryInfoValidationError{
				field:  "Dimensions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetManufacturer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InventoryInfoValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InventoryInfoValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManufacturer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InventoryInfoValidationError{
				field:  "Manufacturer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	{
		sorted_keys := make([]string, len(m.GetMetadata()))
		i := 0
		for key := range m.GetMetadata() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetMetadata()[key]
			_ = val

			// no validation rules for Metadata[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, InventoryInfoValidationError{
							field:  fmt.Sprintf("Metadata[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, InventoryInfoValidationError{
							field:  fmt.Sprintf("Metadata[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return InventoryInfoValidationError{
						field:  fmt.Sprintf("Metadata[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return InventoryInfoMultiError(errors)
	}

	return nil
}

// InventoryInfoMultiError is an error wrapping multiple validation errors
// returned by InventoryInfo.ValidateAll() if the designated constraints
// aren't met.
type InventoryInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InventoryInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InventoryInfoMultiError) AllErrors() []error { return m }

// InventoryInfoValidationError is the validation error returned by
// InventoryInfo.Validate if the designated constraints aren't met.
type InventoryInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InventoryInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InventoryInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InventoryInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InventoryInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InventoryInfoValidationError) ErrorName() string { return "InventoryInfoValidationError" }

// Error satisfies the builtin error interface
func (e InventoryInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInventoryInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InventoryInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InventoryInfoValidationError{}

// Validate checks the field values on Dimensions with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Dimensions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dimensions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DimensionsMultiError, or
// nil if none found.
func (m *Dimensions) ValidateAll() error {
	return m.validate(true)
}

func (m *Dimensions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Length

	// no validation rules for Width

	// no validation rules for Height

	// no validation rules for Weight

	if len(errors) > 0 {
		return DimensionsMultiError(errors)
	}

	return nil
}

// DimensionsMultiError is an error wrapping multiple validation errors
// returned by Dimensions.ValidateAll() if the designated constraints aren't met.
type DimensionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DimensionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DimensionsMultiError) AllErrors() []error { return m }

// DimensionsValidationError is the validation error returned by
// Dimensions.Validate if the designated constraints aren't met.
type DimensionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DimensionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DimensionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DimensionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DimensionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DimensionsValidationError) ErrorName() string { return "DimensionsValidationError" }

// Error satisfies the builtin error interface
func (e DimensionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDimensions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DimensionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DimensionsValidationError{}

// Validate checks the field values on Manufacturer with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Manufacturer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Manufacturer with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ManufacturerMultiError, or
// nil if none found.
func (m *Manufacturer) ValidateAll() error {
	return m.validate(true)
}

func (m *Manufacturer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Country

	// no validation rules for Website

	if len(errors) > 0 {
		return ManufacturerMultiError(errors)
	}

	return nil
}

// ManufacturerMultiError is an error wrapping multiple validation errors
// returned by Manufacturer.ValidateAll() if the designated constraints aren't met.
type ManufacturerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManufacturerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManufacturerMultiError) AllErrors() []error { return m }

// ManufacturerValidationError is the validation error returned by
// Manufacturer.Validate if the designated constraints aren't met.
type ManufacturerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManufacturerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManufacturerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManufacturerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManufacturerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManufacturerValidationError) ErrorName() string { return "ManufacturerValidationError" }

// Error satisfies the builtin error interface
func (e ManufacturerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManufacturer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManufacturerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManufacturerValidationError{}

// Validate checks the field values on Value with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Value) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Value with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ValueMultiError, or nil if none found.
func (m *Value) ValidateAll() error {
	return m.validate(true)
}

func (m *Value) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Kind.(type) {
	case *Value_StringValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for StringValue
	case *Value_Int64Value:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Int64Value
	case *Value_DoubleValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for DoubleValue
	case *Value_BoolValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for BoolValue
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ValueMultiError(errors)
	}

	return nil
}

// ValueMultiError is an error wrapping multiple validation errors returned by
// Value.ValidateAll() if the designated constraints aren't met.
type ValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValueMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValueMultiError) AllErrors() []error { return m }

// ValueValidationError is the validation error returned by Value.Validate if
// the designated constraints aren't met.
type ValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValueValidationError) ErrorName() string { return "ValueValidationError" }

// Error satisfies the builtin error interface
func (e ValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValueValidationError{}
