version: '3'

vars:
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  PROTOC_GEN_GRPC_GATEWAY_VERSION: 'v2.26.3'
  PROTOC_GEN_VALIDATE_VERSION: 'v1.2.1'

  OGEN_VERSION: 'v1.12.0'
  YQ_VERSION: 'v4.45.2'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-grpc-gateway'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'

  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'

  NODE_MODULES_DIR: '{{.ROOT_DIR}}/node_modules/.bin'
  REDOCLY: '{{.NODE_MODULES_DIR}}/redocly'

  OPEN_API_ORDER_V1_BASE: '{{.ROOT_DIR}}/shared/api/order/v1/order.openapi.yaml'
  OPEN_API_ORDER_V1_BUNDLE: '{{.ROOT_DIR}}/shared/api/bundles/order.openapi.v1.bundle.yaml'

  OPEN_API_FILES: '{{.ROOT_DIR}}/shared/api/bundles'

tasks:
  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.BUF}} ] || {
          echo '📦 Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}

  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GRPC_GATEWAY}} ] || {
          echo '📦 Installing protoc-gen-grpc-gateway...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@{{.PROTOC_GEN_GRPC_GATEWAY_VERSION}}
        }
        [ -f {{.PROTOC_GEN_VALIDATE}} ] || {
          echo '📦 Installing protoc-gen-validate...'
          GOBIN={{.BIN_DIR}} go install github.com/envoyproxy/protoc-gen-validate@{{.PROTOC_GEN_VALIDATE_VERSION}}
        }

  proto:update-deps:
    deps: [ install-buf ]
    desc: Обновляет зависимости protobuf из удаленных репозиториев (googleapis и т.д.)
    dir: shared/proto
    cmds:
      - |
        echo "🔄 Обновляем зависимости buf..."
        {{.BUF}} dep update

  proto:gen:
    deps: [ install-buf, proto:install-plugins, proto:update-deps ]
    desc: Генерация Go-кода из .proto
    dir: shared/proto
    cmds:
      - '{{.BUF}} generate'

  redocly-cli:install:
    desc: Установить локально Redocly CLI
    cmds:
      - |
        [ -f {{.REDOCLY}} ] || {
          npm ci
        }

  redocly-cli:order-v1-bundle:
    desc: Собрать OpenAPI в один файл через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - '{{.REDOCLY}} bundle {{.OPEN_API_ORDER_V1_BASE}} -o {{.OPEN_API_ORDER_V1_BUNDLE}}'

  redocly-cli:bundle:
    desc: Собрать все схемы OpenAPI в общие файлы через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - task: redocly-cli:order-v1-bundle

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          mkdir -p {{.BIN_DIR}}
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  yq:install:
    desc: "Устанавливает yq в bin/ при необходимости"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Installing yq...'
          GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }

  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ ogen:install, yq:install ]
    cmds:
      - task: redocly-cli:bundle
      - |
        find {{.OPEN_API_FILES}} -name '*.yaml' -o -name '*.yml' | while read -r file; do
          if [ -f "$file" ] && grep -q 'x-ogen:' "$file"; then
            echo "🚀 Generating from: $file"
            target=$({{.YQ}} e '."x-ogen".target' "$file")
            package=$({{.YQ}} e '."x-ogen".package' "$file")
            echo "📁 Target: $target"
            echo "📦 Package: $package"
            {{.OGEN}} \
              --target "$target" \
              --package "$package" \
              --clean \
              "$file" || exit 1
          fi
        done

  gen:
    desc: "Генерирует код из всех спецификаций (proto + OpenAPI)"
    cmds:
      - task: proto:gen
      - task: ogen:gen