syntax = "proto3";

package auth.v1;

import "common/v1/session.proto";
import "common/v1/user.proto";

option go_package = "github.com/mbakhodurov/homeworks/week6/shared/pkg/proto/auth/v1;auth_v1";

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Whoami(WhoamiRequest) returns (WhoamiResponse);
}

/**
 * Запрос на аутентификацию сессии
 */
message LoginRequest {
  string login = 1;         // Логин пользователя
  string password = 2;      // Пароль пользователя
}

/**
 * Ответ с идентификатором сессии
 */
message LoginResponse {
  string session_uuid = 1;  // UUID активной сессии
}

/**
 * Запрос на информацию о текущей сессии
 */
message WhoamiRequest {
  string session_uuid = 1;  // UUID активной сессии
}

/**
 * Ответ с информацией о текущей сессии и данных о владельце текущей сессии
 */
message WhoamiResponse {
  common.v1.Session session = 1;  // Информация о текущей сесии
  common.v1.User user = 2;        // Владелец текущей сессии
}
