// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type GetAllOrdersRes interface {
	getAllOrdersRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type PaymentOrderRes interface {
	paymentOrderRes()
}
